/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dip_util_guts_NativeUtils */

#ifndef _Included_dip_util_guts_NativeUtils
#define _Included_dip_util_guts_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dip_util_guts_NativeUtils
 * Method:    initStringFieldIds
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_dip_util_guts_NativeUtils_initStringFieldIds
  (JNIEnv *, jclass, jclass);

/*
 * Class:     dip_util_guts_NativeUtils
 * Method:    testStringAccess
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dip_util_guts_NativeUtils_testStringAccess
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dip_util_guts_NativeUtils
 * Method:    testStringAccessHack1
 * Signature: (ICCCCCCCCCCCCCCCC)V
 */
JNIEXPORT void JNICALL Java_dip_util_guts_NativeUtils_testStringAccessHack1
  (JNIEnv *, jclass, jint, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar, jchar);

#ifdef __cplusplus
}
#endif
#endif
