/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dip_util_guts_NativeDataNode */

#ifndef _Included_dip_util_guts_NativeDataNode
#define _Included_dip_util_guts_NativeDataNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dip_util_guts_NativeDataNode
 * Method:    getNativeValue
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_dip_util_guts_NativeDataNode_getNativeValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dip_util_guts_NativeDataNode
 * Method:    setNativeValueNull
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_dip_util_guts_NativeDataNode_setNativeValueNull
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dip_util_guts_NativeDataNode
 * Method:    setNativeValueInt
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_dip_util_guts_NativeDataNode_setNativeValueInt
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     dip_util_guts_NativeDataNode
 * Method:    setNativeValueString
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_dip_util_guts_NativeDataNode_setNativeValueString
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     dip_util_guts_NativeDataNode
 * Method:    getNativeNumberOfAttributes
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_dip_util_guts_NativeDataNode_getNativeNumberOfAttributes
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     dip_util_guts_NativeDataNode
 * Method:    hasNextAttrName
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_dip_util_guts_NativeDataNode_hasNextAttrName
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     dip_util_guts_NativeDataNode
 * Method:    nextAttrName
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dip_util_guts_NativeDataNode_nextAttrName
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     dip_util_guts_NativeDataNode
 * Method:    removeAttrName
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_dip_util_guts_NativeDataNode_removeAttrName
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     dip_util_guts_NativeDataNode
 * Method:    getNodesNum
 * Signature: (JI[B)I
 */
JNIEXPORT jint JNICALL Java_dip_util_guts_NativeDataNode_getNodesNum
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class dip_util_guts_NativeDataNode_DataNodeIterable */

#ifndef _Included_dip_util_guts_NativeDataNode_DataNodeIterable
#define _Included_dip_util_guts_NativeDataNode_DataNodeIterable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class dip_util_guts_NativeDataNode_AttrNameIterable */

#ifndef _Included_dip_util_guts_NativeDataNode_AttrNameIterable
#define _Included_dip_util_guts_NativeDataNode_AttrNameIterable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
